### ISSUE TITLE
[Typo]: React v18.0 블로그 포스팅 내 링크 오타 수정 

### ISSUE THREAD

**Issue by TakhyunKim** [reactjs/ko.react.dev#1009]
### Summary

React v18.0 블로그 문서에서 React Conf 2021 React 18 Keynote 링크가 잘못되어
`페이지를 찾을 수 없습니다` 페이지로 이동합니다.

### Page

https://ko.react.dev/blog/2022/03/29/react-v18

### 문서 내 잘못 링크된 부분

<img width="959" alt="스크린샷 2024-07-21 오전 12 59 27" src="https://github.com/user-attachments/assets/bf03cd11-0f79-4f40-84f3-47342764047a">

### 개발자 도구 내 링크

<img width="513" alt="스크린샷 2024-07-21 오전 1 00 22" src="https://github.com/user-attachments/assets/93816fa1-4bc9-4ddd-befc-8059bc381782">

### 발생 원인 및 해결책

위 문서의 md 파일 코드를 확인해보니 링크 내 `()` 가 하나 더 추가되어 발생한 문제로 확인됩니다. 
`()` 를 삭제하면 정상 동작할 것 같습니다!
<img width="623" alt="스크린샷 2024-07-21 오전 1 08 30" src="https://github.com/user-attachments/assets/04d1b664-a1db-4ddf-8ee9-145fc5906a72">

안녕하세요!
위 내용에서 문제가 없다면 직접 수정 후 PR 올려도 괜찮을까요? :D

**Comment by hg-pyun** [comment]
물론입니다! 잘 부탁드립니다.

**Comment by TakhyunKim** [comment]
넵 작업 후 PR 올리도록 하겠습니다! 😀
