### ISSUE TITLE
[Suggestion]: 자습서: 틱택토 게임 페이지의 로컬 개발 환경 설정의 설명 수정을 제안합니다.

### ISSUE THREAD

**Issue by Hacanna42** [reactjs/ko.react.dev#1028]
### Summary

자습서: 틱택토 게임 페이지의 로컬 개발 환경 설정의 설명에서 "CodeSandBox 탭에서 왼쪽 위 모서리의 버튼을 누르고 메뉴를 열어 Download Sandbox을 선택하여 보관된 파일을 로컬로 내려받으세요" 라고 하는데, 실제로 CodeSandBox의 메뉴에 Download Sandbox라는 옵션은 존재하지 않고, File -> Export to ZIP으로 download 할 수 있는 것으로 확인됩니다.

https://ko.react.dev/learn/tutorial-tic-tac-toe

<img width="937" alt="image" src="https://github.com/user-attachments/assets/4edc1fce-cbad-4de4-98ca-d00271ade8a6">
<img width="522" alt="image" src="https://github.com/user-attachments/assets/9c702fb4-f207-4d3b-a17a-cc94056b9e91">

### Page

https://ko.react.dev/learn/tutorial-tic-tac-toe

### Details

"Download Sandbox을 선택하여 보관된 파일을 로컬로 내려받으세요" 를 "File -> Export to ZIP을 선택하여 보관된 파일을 로컬로 내려받으세요" 로 수정하는 것을 제안합니다.

**Comment by lumirlumir** [comment]
@Hacanna42 안녕하세요😊

해당 내용은 '다운로드' 버튼에 마우스를 올렸을 때 나타나는 툴팁(Download Sandbox)을 의미합니다.

![image](https://github.com/user-attachments/assets/3ff61cca-76b9-4453-8619-8fed9883626d)

다만, 다운로드에 대한 지문이 헷갈리게 되어있어 수정을 고려해볼만 한 것 같습니다.

ko.react.dev는 기본적으로 react.dev의 [영어 원문](https://react.dev/learn/tutorial-tic-tac-toe#setup-for-the-tutorial "react.dev")을 그대로 따라가야 하기에, 해당 내용을 괄호 안에 추가하는 방식을 권장합니다.

```diff
-1. 앞서 열었던 CodeSandBox 탭에서 왼쪽 위 모서리의 버튼을 누르고 메뉴를 열어 **Download Sandbox**을 선택하여 보관된 파일을 로컬로 내려받으세요.
+1. 우측 상단의 **다운로드** 버튼, 또는 앞서 열었던 CodeSandBox 탭에서 왼쪽 위 모서리의 버튼을 누르고 메뉴를 열어 **Download Sandbox**(혹은 **File -> Export to ZIP**)을 선택하여 보관된 파일을 로컬로 내려받으세요.
```

위 내용을 토대로 혹여 PR 의향이 있으실까요?
없으시다면 해당 이슈 반영 후, close하겠습니다.
