### ISSUE TITLE
[Suggestion]: React 공식 문서에 한국어 문서도 번역 완료된 문서로 추가하기

### ISSUE THREAD

**Issue by hcooch2ch3** [reactjs/ko.react.dev#1057]
### Summary

중국어, 일본어처럼 React 공식 문서에 한국어 문서도 번역 완료된 문서로 추가하기

### Page

https://react.dev/community/translations

### Details

안녕하세요. 웹개발하면서 많은 분들이 번역에 기여해주신 한글 React 문서 잘 보고 있습니다.

한가지 제안 드리고 싶은게 있는데, React 공식 문서에 한국어 문서도 번역 완료된 문서로 추가되었으면 어떨가 해서 제안 올려봅니다.

다음 링크 https://github.com/reactjs/react.dev/blob/main/src/utils/finishedTranslations.ts 의 `finishedTranslations.ts` 에 `ko` 를 추가해서 머지하면 될 것 같습니다. 

```javascript
export const finishedTranslations = [
  'en',
  'zh-hans',
  'es',
  'fr',
  'ja',
  'tr',
 'ko' // 한국어 추가
];
```

![image](https://github.com/user-attachments/assets/b590c6ba-e5a8-449e-8707-40f0401e129a)

감사합니다.

**Comment by hcooch2ch3** [comment]
https://github.com/reactjs/react.dev/pull/7185

@lumirlumir 
진행해주셨군요. 감사합니다!

**Comment by lumirlumir** [comment]
아ㅋㅋ 어느새 이슈도 올리셨군요 

다 반영해서 올려놨으니 기다리면 될 것 같습니다!
