### ISSUE TITLE
[번역 필요] React 19 RC

### ISSUE THREAD

**Issue by HojinAn** [reactjs/ko.react.dev#1083]
### Summary
한국어 공식문서 [React 19 RC](https://ko.react.dev/blog/2024/04/25/react-19) 번역 제안

### Page
https://ko.react.dev/blog/2024/04/25/react-19

### Details
안녕하세요!
한국어 공식문서에서 [React 19 RC](https://ko.react.dev/blog/2024/04/25/react-19) 번역되어 있지않은 것으로 확인했는데 해당 페이지 번역을 맡아도 될까요?

10월 내로 완료하겠습니다!

**Comment by lumirlumir** [comment]
네, 잘 부탁드립니다!

**Comment by HojinAn** [comment]
앗.. 업무가 조금 바빠져서 조금 늦어졌습니다 11월 내로 번역 완료하겠습니다!
