### ISSUE TITLE
[번역 필요]: useEffect > caveats 섹션

### ISSUE THREAD

**Issue by julyydev** [reactjs/ko.react.dev#1097]
### Summary

![image](https://github.com/user-attachments/assets/aa8a37ef-0d6a-4a3b-a285-79cf9a9a620a)

### Page

https://ko.react.dev/reference/react/useEffect#caveats

### Details

useEffect의 caveats 섹션에 일부 번역이 되지 않은 부분이 있는 것 같습니다.
제가 해당 부분 번역 진행해도 괜찮을까요?

**Comment by lumirlumir** [comment]
네, 해당 부분은 새롭게 추가된 부분이라 아직 미번역된 상태입니다.

잘 부탁드립니다!
