### ISSUE TITLE
[번역 필요]: blog의 React v19 페이지 번역

### ISSUE THREAD

**Issue by wet6123** [reactjs/ko.react.dev#1108]
### Summary
blog > React v19

### Page
https://react.dev/blog/2024/12/05/react-19

### Details
안녕하세요 해당 페이지 번역 작업이 필요할 것 같은데 제가 해봐도 될까요?
12월 21일 까지 마무리 해보겠습니다.
추가적으로 ko.react.dev에는 아직 이 글이 업데이트 되지 않은 것 같은데 어떻게 가져오면 될까요?

**Comment by lumirlumir** [comment]
> 추가적으로 ko.react.dev에는 아직 이 글이 업데이트 되지 않은 것 같은데 어떻게 가져오면 될까요?

안녕하세요, 원래 주기적으로 PR이 한글 리액트 공식문서로 넘어오는데, 아직 해당 PR이 올라오지 않았습니다.

리액트 영문 공식문서 링크(https://github.com/reactjs/react.dev/tree/main/src/content/blog/2024/12/05)에서 해당 마크다운 파일 복사하시고 번역 후, 한글 공식문서 상에 동일한 디렉토리에 넣어주시면 감사할 것 같습니다!

잘 부탁드립니다🙇‍♂️
