### ISSUE TITLE
Missing docs in the list

### ISSUE THREAD

**Issue by taggon** [reactjs/ko.react.dev#370]
The followings are the missing docs in #1 .
번역 작업 목록( #1 )에 누락된 문서가 있어서 여기에 새로 목록을 추가했습니다.

* [ ] [Legacy Context](https://github.com/reactjs/ko.reactjs.org/blob/main/content/docs/legacy-context.md)
* [ ] [Legacy Event Pooling](https://github.com/reactjs/ko.reactjs.org/blob/main/content/docs/legacy-event-pooling.md)

**Comment by hg-pyun** [comment]
[#374 ](https://github.com/reactjs/reactjs.org/issues/4135#issuecomment-981865846) 에 의하면, 기존 문서 번역작업은 중단하고, 새 문서 번역을 시작하는 것이 좋을 것 같습니다.
