### ISSUE TITLE
[Question] 18 버전 소개 블로그 번역은 언제 진행되나요?

### ISSUE THREAD

**Issue by dodoongtak** [reactjs/ko.react.dev#443]
어디에서 기여할 수 있을까요?

See Also: 
- https://reactjs.org/blog/2022/03/29/react-v18.html

**Comment by hg-pyun** [comment]
react.org 기존 브랜치를 땡겨와야하는데.. 지금 컨플릭 상태를 보니 날잡고 한번 정리해야하긴 합니다 ㅠㅜ 

이 위치에 넣어야 합니다.
https://github.com/reactjs/ko.reactjs.org/tree/main/content/blog

**Comment by dante01yoon** [comment]
버전 18 번역에 참가하고 싶은데 언제쯤 시작 가능할까요?

**Comment by froggal** [comment]
18 버전 번역에 참여하려합니다. 시작되면 바로 참여하겠습니다.

**Comment by hg-pyun** [comment]
beta로 전환해야하는데, 시간이 없어서 작업을 못하고있네요. ㅠ_ㅠ 조만간 챙겨보겠습니다.

**Comment by hg-pyun** [comment]
@dodoongtak blog쪽은 번역 시작해셔도 됩니다!

**Comment by dodoongtak** [comment]
> @dodoongtak blog쪽은 번역 시작해셔도 됩니다!

크으으 바쁘신 와중에 업데이트 해주셔서 감사합니다 :)

**Comment by froggal** [comment]
> @dodoongtak blog쪽은 번역 시작해셔도 됩니다!

저도 가능할까요?
