### ISSUE TITLE
번역 합의가 도출되기 전인 단어들의 통일된 임시 표기법

### ISSUE THREAD

**Issue by eomttt** [reactjs/ko.react.dev#569]
[Translate Glossary](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary) 작성된 시점이 오래되었고 그에 따른 번역은 잘 이루어졌지만 그 이후 새로운 개념들이 들어왔고 (Suspense, Hydration 등) 그에 맞춘 새로운 번역어 합의가 제대로 이루어 지지 않음

> 생명주기(Lifecycle) / Lifecycle(생명주기) / Lifecycle(생명주기, 임시표기)

와 같은 형태로 https://github.com/reactjs/ko.reactjs.org/issues/2 에서 번역 합의가 도출되기 전인 단어들의 통일된 임시 표기법을 정해 놓으면 이후 번역 속도 및 유지 관리 측면에서 좋을 것 같음

### 참고
https://github.com/reactjs/ko.reactjs.org/issues/555#issuecomment-1427024229

@SyingSHY

**Comment by eomttt** [comment]
@goofcode 요거 제가 언제 이슈를 만들어 놨었네요 .
여기서 하시면 될것 같군요

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/pull/599

하면서 추가할만한것들이 보입니다. 여기서 이어서 이야기해보면 좋을것 같네요

- API reference -> API 참고서
- user interfaces -> 사용자 인터페이스
- markup -> 마크업
- interactivity -> 상호작용
- architecture -> 아키텍처
- full-stack -> full-stack (번역하지 않음)

일단 제가 했을때에 애매한 단어들은 위와 같았고 일단 위의 [PR](https://github.com/reactjs/ko.react.dev/pull/599) 에서는 위에 보이는것처럼 번역했습니다.

추가 의견 있으시면 부탁드립니다.

@hg-pyun @taggon @MaxKim-J

**Comment by gnujoow** [comment]
```
API reference -> API 레퍼런스
user interfaces -> 사용자 인터페이스
markup -> 마크업
interactivity -> 상호작용
architecture -> 아키텍처
full-stack -> full-stack (번역하지 않음)
```
기술용어나 라이브러리에서 사용되는 키워드들은 원문그대로, 우리말로 번역때 더 자연스러운것들은 번역하고, 그렇지 않은것들은 음역을하면 어떨까요?

**Comment by eomttt** [comment]
> 

넵 큰 이견 없습니다.
저것만 https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary 요기에 추가하면 될것 같네요

**Comment by gnujoow** [comment]
@eomttt https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary 에 추가했습니다. 확인후 이슈 클로즈 부탁드릴게요!
