### ISSUE TITLE
베타문서 오픈에 따른 공식 문서 번역 현황

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#581]
안녕하세요 여러분.

React의 공식 베타문서가 릴리즈 됨에 따라 많은 변화가 생겼습니다.

- 기존 영문 문서는 legacy 저장소로 아카이빙 되고, react.dev라는 새로운 저장소가 만들어 졌습니다.
- https://github.com/reactjs/ko.reactjs.org/pull/580 SYNC PR부터 beta folder가 사라지게 되었습니다. 이 PR을 머지하면, 기존에 작업했던 레거시 번역 페이지는 사라지게 됩니다. 현재 영문 문서와 동일한 정책을 가져가기엔 여러 제약이 있기 때문에 [이 스레드](https://github.com/reactjs/react.dev/issues/4135#issuecomment-1479242203)에서 논의가 진행중입니다.
- 현재 번역되어있는 베타와 문서 릴리즈한 영문 문서 사이에 큰 차이가 있습니다. 이는 영문 문서의 컨텐츠 생성 속도가 번역 속도를 따라가지 못한 점과 관리가 잘 되지 못한 복합적인 이유로 발생했습니다.

따라서 환경의 변화가 큰 만큼 새로운 번역 환경을 만들어 보고자 합니다.

- 저장소 문제의 해결
  - 이 문제는 위에서 언급한 논의가 어느정도 방향성이 잡히면, 다시 논의해보면 좋을 것 같습니다. 
- 기존에 번역했던 컨텐츠의 해결
  - 기존에 번역했던 컨텐츠를 살리는 것 보다는 양해를 구하고 다시 번역하는 편이 더 좋다는 생각이 듭니다. 기존에 번역을 진행하셨던 분들이 원하신다면, 먼저 배정을 드리고, 일정 기간이 지난 후 부터는 원하시는분께 새로 어사인 하는 정책이면 어떨까 하는생각입니다. 이 부분에 대해서는 의견 부탁드립니다. 🙇 
- 번역에 대한 그라운드 룰 재정비
  - 기존에 그라운드 룰은 있었으나, 꽤 오래전에 작성되어있고 위키에 있어 접근성이 좋지 않기 때문에 잘 간과되고 지켜지고 있지 않았습니다.
  - 새 그라운드룰은 README.md에 작성 후 크게 두가지를 재정비 하고자 합니다.
    - [Best practices for translation](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation) / https://github.com/reactjs/ko.reactjs.org/issues/584
    - [Translate Glossary](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary) / (https://github.com/reactjs/ko.reactjs.org/issues/569)

좋은 의견이 있으시면 언제든 스레드에 남겨주세요! 감사합니다.

**Comment by mphist** [comment]
신규멤버로 참여 가능한가요?

**Comment by hg-pyun** [comment]
@mphist 번역을 말씀하신 거라면 잠시만 기다려주세요!

**Comment by hg-pyun** [comment]
확인해보니 이미 기존에 작성된 문서를 친절하게 바꿔줬군요. 이걸 이대로 사용해보도록 할께요!

https://github.com/reactjs/ko.react.dev/issues/374

**Comment by hg-pyun** [comment]
https://github.com/reactjs/ko.react.dev/issues/374#issuecomment-1523174481 스레드를 기점으로 번역 시작하겠습니다.

**Comment by hjaelee01** [comment]
안녕하세요! 블로그에서 <How to Upgrade to React 18> 포스트 번역을 담당했는데, 번역을 마쳤습니다. README에 적혀 있는 대로 우선 커밋한 상태인데, 그 이후로는 과정이 어떻게 되는 건지 궁금합니다. 모더레이터 분들이 리뷰한 다음 pull request를 만드시는 건가요? pull request를 만들려 했는데 일단 branch가 publish 된 상태여야 가능하더라고요. 이런 작업은 처음이라 어떤 식으로 진행되는 지 알려주시면 감사하겠습니다!😊🙇‍♂️
