### ISSUE TITLE
Best practices for translation 을 정비한다.

### ISSUE THREAD

**Issue by eomttt** [reactjs/ko.react.dev#584]
- https://github.com/reactjs/ko.reactjs.org/issues/581 여기에 언급한대로 [Best practices for translation]( https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation) 요것을 재정비 후 READEME 로 옮기려고 합니다.

**Comment by eomttt** [comment]
이전에 Best practices for translation
https://github.com/reactjs/ko.reactjs.org/issues/27

**Comment by taggon** [comment]
@eomttt 따로 참고한 문서는 없었고 오픈소스 활동(특히 Node.js 한국어 그룹)과 책 번역을 하면서 얻은 제 개인적인 경험을 나름대로 정리한 내용이었습니다.  혹시 필요하면 해당 문서를 재정비하는 데 저도 참여하도록 하겠습니다. 😄

**Comment by eomttt** [comment]
@taggon 넵 감사합니다.
제가 영어가 부족해서 다음과 같은 계획으로 진행하려고 합니다.
1. https://github.com/reactjs/ko.reactjs.org/issues/27 바탕으로 메인페이지 좀 번역
2. 번역과정에서 추가하거나 좀 다듬을것이 있다면 수정
3. 수정 후 PR <- 요때 같이 참여해주셔도 될것 같습니다

**Comment by eomttt** [comment]
요것은 https://github.com/reactjs/ko.react.dev/pull/599 여기서 이야기한 바와 같이 크게 수정하거나 손 볼 만한것이 없어보이네요
추후에 번역 PR 들이 올라오면 그때 수정하면 좋을것 같습니다.
