### ISSUE TITLE
용어 사전: browser extension

### ISSUE THREAD

**Issue by taggon** [reactjs/ko.react.dev#610]
# 논의하고자 하는 용어

`browser extension` => `브라우저 확장 프로그램`으로 제안합니다.

# 해당 용어가 등장하는 원문의 문장

#608 

```
The easiest way to debug websites built with React is to install the React Developer Tools browser extension. It is available for several popular browsers:
```

기존에는 `확장 기능`이라는 용어가 많이 사용되었고 해당 번역에 대해서 개인적으로 큰 이견은 없습니다. 하지만, 가장 점유율이 높은 구글 크롬 웹 브라우저에서 `확장 프로그램`이라는 용어를 사용하고 있기에 이를 따르는 것이 일관성 측면에서 좋을 것이라 생각합니다.

![image](https://user-images.githubusercontent.com/212034/235569506-dc8bccc1-fa64-4cce-baf0-7511a90606de.png)

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by wonjin-dev** [comment]
확인했습니다 : )

`가장 점유율이 높은 구글 크롬 웹 브라우저에서 확장 프로그램이라는 용어를 사용하고 있기에 이를 따르는 것이 일관성 측면에서 좋을 것` 많이 공감됩니다 ! 

https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary 

관련 PR도 진행해도 될까요 ?

**Comment by gnujoow** [comment]
제안에 동의합니다.

**Comment by taggon** [comment]
위키에 [업데이트](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary) 해두었으므로 이 논의는 닫겠습니다. 😄
