### ISSUE TITLE
용어: parameter와 argument

### ISSUE THREAD

**Issue by taggon** [reactjs/ko.react.dev#614]
# 논의하고자 하는 용어

함수의 정의와 호출에서 많이 사용되는 `parameter`와 `argument`라는 용어에 관해 정의하고자 합니다.
[MDN의 번역 사례](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Functions#%EC%9D%B8%EC%88%98arguments_%EA%B0%9D%EC%B2%B4_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)에 따라 다음과 같이 제안합니다.

| 용어           |  번역어  |
|-----------|---------|
| parameter | 매개변수 |
| argument  | 인수       |

# 해당 용어가 등장하는 원문의 문장

#612 

```
### Parameters

The function value that you want to cache. It can take any arguments and return any values.
```

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [x] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by gnujoow** [comment]
제안에 동의합니다. argument의 경우 전달인자, 인자로도 변역될수 있는데, 올려주신 MDN과 https://learn.microsoft.com/ko-kr/dotnet/visual-basic/programming-guide/language-features/procedures/differences-between-passing-an-argument-by-value-and-by-reference 사례를 봣을때 인수가 더 적절한 표현인것 같습니다.

**Comment by hg-pyun** [comment]
저도 동의해요 👍

**Comment by taggon** [comment]
두 분이 동의해주셔서 용어를 업데이트 해두었습니다. 감사합니다.
