### ISSUE TITLE
용어: Reference

### ISSUE THREAD

**Issue by goofcode** [reactjs/ko.react.dev#615]
# 논의하고자 하는 용어
**Reference: 레퍼런스**

원문에서 구체적인 명세를 나타내기 위해서 자주 사용 되고 있는데요,
[여기](https://github.com/reactjs/ko.react.dev/issues/569#issuecomment-1528999309) 에서 논의된 것과 유사하게 그대로 `레퍼런스` 로 음역하면 어떨까 합니다.

일반적으로 사용하는 `참고` 또는 `참조` 등도 고려해 볼 수 있을 것 같은데, 의견 부탁드려봅니다.

# 해당 용어가 등장하는 원문의 문장
#607 

```
## Reference {/*reference*/}

### `<progress>` {/*progress*/}

To display a progress indicator, render the [built-in browser `<progress>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) component.
```

#612

```

## Reference {/*reference*/}

### `useCallback(fn, dependencies)` {/*usecallback*/}

Call `useCallback` at the top level of your component to cache a function definition between re-renders:
```

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by hg-pyun** [comment]
일반적으로 IT 업계에서도 레퍼런스라고 많이 쓰는 만큼 그대로 음역해도 좋을 것 같습니다.

**Comment by hg-pyun** [comment]
Glossary에는 이미 반영되어 있군요. 👀 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/10627668/236382172-3ba401cd-7860-453a-8034-fd1ff9ab1d30.png">

**Comment by eomttt** [comment]
Glossary 에 제가 넣었습니다.
API reference 이야기하면서
