### ISSUE TITLE
용어: React 용어의 혼용

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#618]
# 논의하고자 하는 용어
React 단어가 `리액트` 혹은 `리엑트` 혹은 `React` 각각 다르게 번역되고 있습니다. 용어의 통일을 위해 Glossary에도 적어두면 좋을 것 같아요. 고유명사이다 보니 `React`를 그대로 쓰는게 좋을 것 같다는 생각입니다.

# 해당 용어가 등장하는 원문의 문장
- https://github.com/reactjs/ko.react.dev/pull/616/files#diff-6ce371bedd94ba715b4a14b0486125af9846671bce6a7d285ca7589f367b2262R7

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by eomttt** [comment]
React 를 그대로 쓰는것에 한표 던집니다!

**Comment by goofcode** [comment]
> React 를 그대로 쓰는것에 한표 던집니다!

저도 같은 의견입니다 🙇

**Comment by gnujoow** [comment]
제안에 동의합니다. 고유 명사는 원문으로 쓰는게 좋겠습니다.

**Comment by taggon** [comment]
저도 `React` 그대로 사용하는 것에 한 표 더합니다.

**Comment by hg-pyun** [comment]
반영해뒀습니다. 🙇‍♂️
