### ISSUE TITLE
용어: Loading indicators

### ISSUE THREAD

**Issue by 1ilsang** [reactjs/ko.react.dev#630]
# 논의하고자 하는 용어

https://github.com/reactjs/ko.react.dev/pull/609#discussion_r1185700974 에서 진행된 내용입니다.

Loading indicators: 로딩 인디케이터

`로딩 표시기` 혹은 `로딩 영역` 보다 `로딩 인디케이터`로 음역하는게 어떨까요? '인디케이터' 명칭을 많이 사용하고 있다고 생각해 제안드립니다.

# 해당 용어가 등장하는 원문의 문장

https://github.com/reactjs/ko.react.dev/pull/609/files#diff-65e4a4ed93a8aea77fb640c76a54bce866f88cab7241d7768e9ac806e4366353L710

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by hg-pyun** [comment]
인디케이터를 대체할만한 적당한 단어가 떠오르지 않는군요. 저는 찬성입니다.

**Comment by eomttt** [comment]
전찬성
