### ISSUE TITLE
용어: Drilling

### ISSUE THREAD

**Issue by Jincy7** [reactjs/ko.react.dev#631]
# 논의하고자 하는 용어

https://github.com/reactjs/ko.react.dev/pull/628#discussion_r1191842035  에서 제안된 내용입니다.

drilling: 드릴링

Prop을 여러 컴포넌트에 거쳐 내려주는 특정 상황을 drilling 이라는 단어로 실무에서도 많이 표현해 `드릴링`으로 음역하고자 합니다.

한가지 논의해 보고싶은 점은 문맥상 `Prop drilling`을 뜻하는 경우에만 `Prop 드릴링`이라고 음역할지에 대해서 입니다. 자주 쓰이는 표현인지는 잘 모르겠지만 혹시 drilling 이 단독으로 본래 의미로 사용된 경우 혼란을 줄 수도 있을 것 같습니다.

# 해당 용어가 등장하는 원문의 문장

https://github.com/reactjs/ko.react.dev/pull/628/files/02f19034f0099b1bb16039f3e4657297e17e07dc#diff-b6b5ea0aed3adaaf0180558ddb8f3b22c13b106e27c5b627606636d97d3b6018L35

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by eomttt** [comment]
저는 그냥 props drilling 이라고 원문 그대로 쓰는것이 더 나을것 같아요
오히려 번역해서 더 어색해지는것 같습니다

**Comment by hg-pyun** [comment]
저도 props drilling에 한표입니다!

**Comment by Jincy7** [comment]
넵 Prop drilling 은 번역하지 않고 원문 그대로 사용하도록 하겠습니다.

Translate Grossary에 `번역하면 안되는 용어` 에 추가가 필요할까요?

**Comment by hg-pyun** [comment]
@Jincy7 네 추가해 두겠습니다!
