### ISSUE TITLE
용어: ExpandableCallout 내에 있는 다양한 용어

### ISSUE THREAD

**Issue by eomttt** [reactjs/ko.react.dev#632]
# 논의하고자 하는 용어
src/components/MDX/ExpandableCallout.tsx 내에 있는 다양한 용어

- 'deprecated' 
- pitfall' 
- 'note' 
- 'wip'

# 해당 용어가 등장하는 원문의 문장
- 종종 보이는 ExpandableCallout 라고 불리는 컴포넌트에 title 영역인것 같네요

<img width="981" alt="스크린샷 2023-05-13 오전 11 22 06" src="https://github.com/reactjs/ko.react.dev/assets/22593217/6a34a0ad-a253-4705-98f9-ecce7252cf20">

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by gnujoow** [comment]
각 내용이 나오는 문서의 맥락을 알면 더 좋을것 같은데 다음과 같이 제안해봅니다.

'deprecated' - 더 이상 사용되지 않습니다.
pitfall' - 주의하세요!
'note' - 중요합니다!
'wip' - 개발중이에요.

**Comment by hg-pyun** [comment]
@eomttt @gnujoow 저도 좋습니다. Glossary에 반영 부탁드려요!

**Comment by hg-pyun** [comment]
제가 반영해 뒀습니다.
