### ISSUE TITLE
용어: Batching

### ISSUE THREAD

**Issue by eomttt** [reactjs/ko.react.dev#636]
# 논의하고자 하는 용어
- state 업데이트에 대한 batching 이야기가 나오는데, 일괄 처리 같은걸로 번역하기 보다는 batching 으로 그대로 써보는것을 제안해봅니다

# 해당 용어가 등장하는 원문의 문장
- https://github.com/reactjs/ko.react.dev/pull/633#pullrequestreview-1425489866

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4

번역하면 안되는 용어에 제안해봅니다

**Comment by hg-pyun** [comment]
Glossary 에 반영해들께요~
