### ISSUE TITLE
Label 정리하기

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#638]
현재 PR에서 사용하고 있는 Label 중에 유의미하지 않은 것들을 정리해보면 좋을 것 같습니다

- beta: 더이상 사용하지 않으므로 제거
- needs review: PR자체가 리뷰가 필요하므로 중복
- needs author response: 이것 역시 comment, change request, approved가 같은 의미를 나타내므로 제거
- ready to merge: approved와 중복

그밖에 새로 추가되면 좋을 법한 Label 이 있다면 의견주시면 감사하겠습니다. 🙇‍♂️

**Comment by taggon** [comment]
`needs author response`는 "이미 누군가 검토했고 PR 작성자의 응답을 기다리는 중이다"라는 정보를 줄 수 있다고 생각합니다. 다른 리뷰어들의 시간을 절약해 줄 수 있을테고 혹시나 코멘트 내용을 잘못 보고 승인하는 경우도 방지할 수 있을 거 같습니다. `Change Request`로 하기에는 조금 애매한데 의견이 필요한 경우도 있지 않을까요?

나머지 레이블은 없애는 데 동의합니다.

**Comment by hg-pyun** [comment]
@taggon 넵 그럼, `needs author response` 태그만 남겨두고 일단 나머지는 제거해보도록 하겠습니다. 🙇‍♂️

**Comment by eomttt** [comment]
번역자가 번역 완료 해서 리뷰어가 다시 확인해야하는 경우도 필요할것 같은데 일단 ready to merge 를 붙여놨습니다
확인후 머지 하면 될것 같아요

**Comment by lumirlumir** [comment]
@hg-pyun 안녕하세요😊 혹시 현재 이슈 해결 완료되었나요? 해결 완료되었으면 close 하려 합니다!

그리고 추가적으로, `needs author response` 이외에 `stale` 이라는 태그도 추가했으면 합니다.

현재 이슈 목록을 보니 번역 하신다고 요청하셨지만 몇 달이나 지난 이슈들이 많아서, 해당 이슈들에는 `stale` 태그를 붙여두고 번역자 분이 일정 기간 응답이 없으실 경우 close 하려 합니다.
