### ISSUE TITLE
용어: memoization, memoized

### ISSUE THREAD

**Issue by eomttt** [reactjs/ko.react.dev#639]
# 논의하고자 하는 용어
- `memo` 를 써서 메모화된 컴포넌트를 이야기할 때에 사용되는 용어
- memoization, memoized
- 메모화, 메모화된 이라고 번역하는데 번역하지 않고 원문 그대로 쓰는것은 어떨까 제안해봅니다.

# 해당 용어가 등장하는 원문의 문장
https://github.com/reactjs/ko.react.dev/pull/634#pullrequestreview-1425491493

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/pull/634#discussion_r1193080768

**Comment by hg-pyun** [comment]
방금 리뷰한 PR에 있었는데 거기에도 반영을 해야할 것 같군요. 저는 찬성입니다.
