### ISSUE TITLE
Wiki Best practices for translation의 부제목에 작은따옴표 추가 

### ISSUE THREAD

**Issue by 2taesung** [reactjs/ko.react.dev#694]
Wiki의 Best practices for translation 를 읽는 중 순간 놀란 문장이 있어 issue 올립니다!

부제목 [당신과 여러분은 없어도 됩니다.] 에 '당신', '여러분' 키워드의 구분이 없어
부제목만 읽었을 경우 해당 글을 읽는 독자를 향해 없어도 된다. 라고 순간적으로 오해할 수 있을 것 같습니다.
물론 글을 이어서 읽는다면 당연히 오해가 풀리겠지만요...!

그래서 현 [당신과 여러분은 없어도 됩니다.] 에 작은따옴표를 추가해
['당신'과 '여러분'은 없어도 됩니다.] 나 ['당신'과 '여러분' 키워드는 없어도 됩니다.] 로 변경하면 어떨까 제안합니다!

**Comment by hg-pyun** [comment]
오 매우 공감합니다. 요건 제가 반영해두도록 하겠습니다.
