### ISSUE TITLE
용어: logic

### ISSUE THREAD

**Issue by 2taesung** [reactjs/ko.react.dev#695]
# 논의하고자 하는 용어
logic 을 단순 번역하면 논리 로 번역되는데 Computer Science에서 logic은 단순 '논리'로 정의할 수 없습니다.
번역하면 안되는 용어로 읽는 법 '로직' 으로 추가하면 어떨까 합니다.

# 해당 용어가 등장하는 원문의 문장
https://react.dev/learn/extracting-state-logic-into-a-reducer 의 제목 

`Extracting State Logic into a Reducer`
---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by shiblijamal10** [comment]
can u please put the description in English as it would be easy to understand the issue...

**Comment by 2taesung** [comment]
> can u please put the description in English as it would be easy to understand the issue...

I think that the English word 'logic' should not be used as a simple Korean translation.
So, I suggest expressing it as it sounds in Korean.

**Comment by eomttt** [comment]
죻습니다

**Comment by taggon** [comment]
"로직"은 음차해서 많이 사용되는 것 같아서 그대로 한국어 "로직"이라고 번역하면 좋겠다는 의견을 내어봅니다.

----

@shiblijamal10 Every issue labelled with `term` is a discussion about new Korean translation terms, so non-Korean speaker may not need to understand the issue. 😄

**Comment by hg-pyun** [comment]
[Translate-Glossary](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary)의 "일반" 부분에 추가해 뒀습니다. 이 이슈는 기존 logic, 또는 논리로 번역된 단어들을 "로직"으로 변경이 완료되면 닫도록 하겠습니다. 🙇‍♂️
