### ISSUE TITLE
yarn dev 실행 시 에러

### ISSUE THREAD

**Issue by hjaelee01** [reactjs/ko.react.dev#702]
로컬 리포에서 `git pull origin main`를 실행한 다음, `yarn dev`를 실행하니 터미널과 원래 정상적으로 접속되어야 할 'http://localhost:3000'에 갑자기 에러가 뜹니다. 제 머신이 이상한 건지, `git pull`해 온 버전이 이상한 건지 모르겠네요.
에러 메시지로 봐서는, node modules 파일에 있는 dependency 문제인 듯 싶습니다.
제 담당 문서가 아닌 이상 터치하면 혹시 문제가 생길까 해서 이슈 올려봅니다. 감사합니다!
1. 터미널 화면
![터미널 화면](https://github.com/reactjs/ko.react.dev/assets/102636119/da2479c7-865f-4565-919b-f40710e304a4)
2. 로컬 호스트 화면에 뜬 에러
![로컬 호스트 화면](https://github.com/reactjs/ko.react.dev/assets/102636119/9503b954-994a-4884-8d2d-45e46a43edbd)

**Comment by hg-pyun** [comment]
홀리몰리

**Comment by woochanleee** [comment]
@hjaelee01 방금 `git clone` 후 `yarn install & yarn dev` 로 실행 해봤는데 올려주신 이슈가 재현되진 않네요 😢 
말씀하신대로 `git pull` 또는 `node_modules` 설치 과정에서 문제가 의심되긴 하는데 더 파악해볼 여지가 딱히 없어보이군요.
깨끗한 상태로 다시 시도해보시고, 동일한 이슈가 재현된다면 re-open 해주시면 될것 같습니다! cc. @hg-pyun 

올려주신 로그에 남은 [Multiple children were passed ...](https://nextjs.org/docs/messages/link-multiple-children) 에러는 코드베이스 내 [이 부분](https://github.com/reactjs/ko.react.dev/blob/1b5e8861ab40d94e030bff0100708106c4689603/src/components/Layout/Sidebar/SidebarLink.tsx#L74-L88) 에서 발생할수 있어 보이긴 합니다. 다만 [link.tsx
](https://github.com/vercel/next.js/blob/v13.4.1/packages/next/src/client/link.tsx#L478-L503) 를 보시면 `legacyBehavior` flag 가 켜진 경우에만 해당 로직이 실행되어서 이것도 문제는 아닌것 같네요. 이 flag 를 강제로 키면 동일한 에러가 발생하나 같은 상황 인지는 확실하지 않아서 기록만 해두겠습니다.

**Comment by hjaelee01** [comment]
**해결됐습니다!**
알고 보니 어이없게도 제가 `yarn install`을 먼저 실행하지 않은 게 원인이었습니다.😭
Dependency 문제였던 것 같네요. 다른 분들은 저 같은 실수로 시간낭비하진 않길 바랍니다. 감사합니다!
