### ISSUE TITLE
용어: Suspense 

### ISSUE THREAD

**Issue by sa02045** [reactjs/ko.react.dev#705]
# 논의하고자 하는 용어
`Suspense`를 [번역하면 안되는 용어](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4)에 추가하는 것을 제안합니다. (이미 #681 에 반영되었음)

# 해당 용어가 등장하는 원문의 문장

#681 

```
You can reduce the portion of the route that is client-side rendered by wrapping the component that uses `useSearchParams` in a `Suspense` boundary. For example:
```

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by gnujoow** [comment]
동의합니다. 계념을 담고 있는 용어이므로 고유명사로 작성하고 번역하지 않는게 좋겟습니다.

**Comment by hg-pyun** [comment]
반영해뒀습니다. 기존에 서스펜스로 번역된 글들 -> suspense로 바꿔서 반영한 후에 이 PR을 닫도록 하겠습니다.
