### ISSUE TITLE
용어: Returns

### ISSUE THREAD

**Issue by taggon** [reactjs/ko.react.dev#725]
# 논의하고자 하는 용어

Returns: 주로 함수를 설명의 소제목으로 사용되어 함수에서 반환하는 값을 의미합니다.
현재 `반환`, `반환값`, `반환 값`(띄어쓰기) 등 다양하게 번역되어 있습니다.

원문은 다르지만 의미가 같은 [한국정보통신기술협회의 사례](https://terms.tta.or.kr/dictionary/dictionaryView.do?subject=%EB%B0%98%ED%99%98%EA%B0%92)에 따라 `반환값`으로 통일하였으면 합니다.

# 해당 용어가 등장하는 원문의 문장

```markdown
#### Returns {/*returns*/}
-- 
`lazy` returns a React component you can render in your tree. While the code for the lazy component is still loading
```

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [x] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by hg-pyun** [comment]
사례에 근거해서 좋네요..! 반환값으로 일괄 반영한 후 이 이슈를 닫으면 좋을 것 같습니다 🙇‍♂️

**Comment by taggon** [comment]
용어 사전에 업데이트 해두었습니다.
