### ISSUE TITLE
용어: Escape Hatches

### ISSUE THREAD

**Issue by da-in** [reactjs/ko.react.dev#738]
# 논의하고자 하는 용어
**Escape Hatches** 
Side Bar에서 번역되지 않고 `Escape Hatches`로 기술되어있어 이슈 남깁니다.  
_It is not translated from the side bar and is described as 'Escape Hats', so it leaves an issue._

# 해당 용어가 등장하는 원문의 문장

- #737

learn > chapter 4's Title
```
Escape Hatches
```
현재 다른 컨트리뷰터 분들이 다른 부분에서 `탈출구`와 `해결책` 으로 번역한 것을 확인했습니다.  
_Now, I've seen other translators translate it into mean like 'exit' and 'solution' in different parts._

**Edited Case 1** : Learn > Chapter 3 : Managing State
```
Or, if you’re already familiar with these topics, why not read about Escape Hatches?
이 주제에 이미 익숙하다면 해결책(Escape Hatches)에 대해서 읽어보는 것은 어떨까요?
```
**Edited Case 2.** : Learn > Chapter 3 : Escape Hatches > You Might Not Need an Effect
```
Effects are an escape hatch from the React paradigm.
Effect는 React 패러다임에서 벗어날 수 있는 탈출구입니다.
```

탈출구와 해결책 중 무엇이 적합한 표현인 지 논의하고 싶습니다.  
_I would like to discuss which is a more appropriate expression, an means like exit or a solution._

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by devjiwonchoi** [comment]
> In this chapter, you’ll learn the escape hatches that let you “step outside” React and connect to external systems.

문맥 상 React 내에 국한 되지 않고 "벗어나다", "빠져 나오다"에 중점을 둔 단어 같아서, Escape Hatch를 직역한 `탈출구`에 한 표 던지겠습니다.

**Comment by hg-pyun** [comment]
해결책도 괜찮은 의역같은데 요건 판단이 잘 안서는군요 ㅋㅋ... 탈출구로 표현해도 이해하는데 어렴움은 없어 보이긴합니다. 다른분들 의견도 들어보고 싶습니다. @MaxKim-J @emottt

**Comment by eomttt** [comment]
흐음 전 개인적으로는 번역하지 않는것이 더 좋다고 생각하긴 합니다.
Escape Hatches 라는 용어 자체의 의미가 있다고 생각하는데요 약간 useEffect 나 Effect 를 효과로 의역해서 쓰지 않는것 처럼 번역하지 않는 방향이 더 좋아보이네요

https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

여기에서도 애매한 친구들은 번역하지 않는데 같은 결이 아닐까 싶습니다

**Comment by eomttt** [comment]
그렇다면 전 탈출구도 좋습니다!

**Comment by eomttt** [comment]
별 이견 없으신것 같아서 `탈출구` 로 의역하는것으로 적어놓겠습니다.

@da-in 감사합니다

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#react
