### ISSUE TITLE
용어: Cleanup Function

### ISSUE THREAD

**Issue by da-in** [reactjs/ko.react.dev#739]
# 논의하고자 하는 용어
`clean up`, `cleanup function`

# 해당 용어가 등장하는 원문의 문장

- #737 

> Many Effects also “**clean up**” after themselves. For example, an Effect that sets up a connection to a chat server should return a **cleanup function** that tells React how to disconnect your component from that server:

> In development, React will immediately run and **clean up** your Effect one extra time. ... This ensures that you don’t forget to implement the **cleanup function**.

`cleanup function`은 현재 `정리 함수`와 `클린업 함수` 두 가지로 번역되고 있고. `clean up`은 `정리` 와 `클린업` 두 가지로 번역되고 있습니다. 어느 방향으로 통일하는 것이 좋을지 의논하고 싶습니다.
_In `clean up function` and `clean up`, I would like to discuss whether it is better to write clean up as a unique noun or translate the meaning into Korean._

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by hg-pyun** [comment]
"정리"의 의미가 다양해서 "정리"로 번역했을때는 약간 어색한 표현이 되는 것 같아요. 클린업 같은 경우에는 현업에서도 많이 쓰는 용어니 의역없이 그대로 가도 좋을 것 같다는 생각입니다.

**Comment by da-in** [comment]
클린업 그대로 사용하는 것에 동의합니다! :)

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

여기에도 번역하지 않은 용어로 적어주시고 이슈 클로즈하면 될것 같네요 @da-in

**Comment by da-in** [comment]
@eomttt 위키 업데이트 권한이 없는 듯 하여, 메인테이너 분들께서 업데이트 후 클로즈 해주시는 것으로 알면 될까요🙂

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4

@da-in 감사합니다 번역하면 안되는 용어에 추가하였습니다
