### ISSUE TITLE
[번역 필요] State: A Component's Memory

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#746]
State: A Component's Memory 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by 3people** [comment]
이 페이지 번역 희망합니다

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by 3people** [comment]
> 잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

안녕하세요 9/15까지 작업하겠습니다

**Comment by hg-pyun** [comment]
@3people 안녕하세요, 혹시 작업 상황이 어떻게 되고 있는지 공유 부탁드려도 될까요?

**Comment by 3people** [comment]
> @3people 안녕하세요, 혹시 작업 상황이 어떻게 되고 있는지 공유 부탁드려도 될까요?

안녕하세요. 
먼저 작업이 늦어진 점 죄송합니다. 작업 일정은 금주 주말 내로 마무리해서 PR 올리도록 하겠습니다. 
감사합니다.
