### ISSUE TITLE
[번역 필요] Choosing the State Structure

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#747]
Choosing the State Structure 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by da-in** [comment]
작업하고 싶습니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by da-in** [comment]
> 잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

Due Date는 여유 있게 9월 15일로 잡되, 그 전에 최대한 빠르게 작업 진행하겠습니다. 🙂

**Comment by hg-pyun** [comment]
@da-in 님 안녕하세요! 혹시 작업 상황이 어떻게 되가고 있는지 공유 부탁드려도 될까요?

**Comment by da-in** [comment]
@hg-pyun 안녕하세요. 늦어져서 죄송합니다. 작업 마무리하여 오늘 PR 올릴 예정입니다!🙇🏻‍♀️
