### ISSUE TITLE
[번역 필요] Lifecycle of Reactive Effects

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#748]
Lifecycle of Reactive Effects 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by kingyong9169** [comment]
제가 해보고 싶습니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by kingyong9169** [comment]
> 잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

9월 16일까지 작업해보겠습니다!

**Comment by kingyong9169** [comment]
@ojj1123 안녕하세요, 코멘트 확인했는데요. 제가 번역에 기여하고자 하는 것은 영문서를 번역하며 헷갈리는 부분 4 ~ 5번 확인하면서 더 꼼꼼히 학습하고 한국 react사용자들에게 선한 영향력을 미칠 수 있도록 하는 목적이 큽니다. 이미 많은 부분들을 작업해주셨고 저에게 도움을 주실 수도 있지만 저에게는 오히려 도움으로 다가오지는 않는 것 같습니다.. 오랜 기간동안 많은 부분들을 작업하셔서 아쉬운 마음이 있으실 것 같습니다..

한 가지 더 말씀드리자면, 저는 `[번역 필요]` 이슈들이 다른 컨트리뷰터분들에게 할당되기 이전에 어떤 것들을 작업하고 싶은지 내용들을 살펴보았고 고민 끝에 `Lifecycle of Reactive Effects` 를 선택하게 되었습니다. 만약 @ojj1123님께서 대부분 작업하셨다는 것을 메인테이너분들에게 알리셨고 제가 그 사실을 알았다면 다른 이슈를 선택했을 겁니다. 만약 이미 작업하셨던 부분을 이어서 제가 진행하는 것은 납득하기 어렵다는 말씀을 드리고 싶습니다. 양해 부탁드립니다.

**Comment by ojj1123** [comment]
@kingyong9169 
안녕하세요 :) 코멘트 확인 감사합니다!
동용님 코멘트에 많은 고민이 느껴지네요. 그저 제 작업이 도움이 될까 싶어 말씀드린거고 그 외 의도는 없었습니다~!
잘 부탁드려요 👍

**Comment by hg-pyun** [comment]
@ojj1123 님 안녕하세요! 일단 번역을 진행해주셔서 정말 감사합니다. 다만, 부득이하게 번역이 더디게 진행된 부분에 대해서는 [재할당](https://github.com/reactjs/ko.react.dev/issues/374#issuecomment-1648932700)을 하게 되었습니다. 이미 번역하신 부분에 대해서 기여가 가능한 부분에 대해서 고민을 해봤는데, 한번 쭉 번역작업을 하신 경험으로 더욱 꼼꼼한 리뷰가 가능하지 않을까 하는 생각이 들었습니다. 추후에 @kingyong9169 님이 번역해주시면 코드리뷰 형태로 참여를 한번 부탁드려도 될까요? 🙏  assignee로 별도로 지정해 놓도록 하겠습니다! 

별도로 아직 열려있는 티켓에 대해서 새롭게 기여해주셔도 좋습니다.

공지가 나갔을 시점에 스레드가 워낙 노이즈한 알림이 많아서 놓치셨을 것이란 생각이 듭니다. 이 부분에 대해서는 양해를 구합니다. 참여해주셔서 정말 감사합니다. 🙇‍♂️

**Comment by ojj1123** [comment]
@hg-pyun 
> 추후에 @kingyong9169 님이 번역해주시면 코드리뷰 형태로 참여를 한번 부탁드려도 될까요? 🙏 assignee로 별도로 지정해 놓도록 하겠습니다!

네 @kingyong9169 님이 PR 올리시면 코드리뷰 진행하도록 할게요! 저도 번역하면서 고민했던 부분이 많아서 제가 주도적으로 리뷰 진행하면 도움될거라 생각해요 :) assignee 지정해주시면 감사하겠습니다 ~

코멘트 확인 감사합니다~!

**Comment by hg-pyun** [comment]
@kingyong9169 님 안녕하세요, 혹시 작업상황이 어떻게 되가고 있는지 공유 부탁드려도 될까요?

**Comment by kingyong9169** [comment]
@hg-pyun 안녕하세요, 최근에 바빠져서 작업하다가 조금 지연되었습니다.. 지연된 점 정말 죄송합니다. 번역은 50% 정도 진행되었고 다음주 내로 작업해서 PR 올리도록 하겠습니다.

**Comment by hg-pyun** [comment]
@kingyong9169 님 Due Date를 정해주시면 좋을 것 같습니다..!

**Comment by kingyong9169** [comment]
> @kingyong9169 님 Due Date를 정해주시면 좋을 것 같습니다..!

PR 올려두었습니다! 작업이 조금 지연돼서 죄송합니다..

**Comment by hg-pyun** [comment]
확인했습니다. 감사합니다!
