### ISSUE TITLE
[번역 필요] useEffect

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#749]
useEffect 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by shinel94** [comment]
혹시 작업 듀데이트를 알 수 있을 까요?

**Comment by hg-pyun** [comment]
@shinel94 님 안녕하세요! 정해진 Due Date는 없습니다. 직접 정해주시면 됩니다.

**Comment by hg-pyun** [comment]
@shinel94 정해지시면 스레드로 부탁드립니다!

**Comment by hg-pyun** [comment]
@shinel94 님 안녕하세요, 답변이 없으셔서 혹시 바쁘시면 다른분께 할당드릴 수 있도록 하겠습니다. 오늘까지 의견 부탁드려요! 🙇‍♂️

**Comment by shinel94** [comment]
@hg-pyun 아 답변 못한점 죄송합니다. 제가 다른 업무가 많아서 금번에는 힘들 것으로 예상됩니다. 번거롭게해서 죄송합니다.

**Comment by 2duckchun** [comment]
안녕하세요. useEffect도 제가 작업해볼 수 있을까요?

**Comment by hg-pyun** [comment]
@2duckchun 넵 가능합니다. 예상되는 작업 일정을 스레드에 남겨주세요!

**Comment by 2duckchun** [comment]
마감기한은 10월 20일으로 하되, 빠르게 진행해보겠습니다!

**Comment by hg-pyun** [comment]
옙 감사합니다! useEffect 중요한 개념이다보니 잘 부탁드려봅니다 🙇‍♂️

**Comment by 2duckchun** [comment]
잘부탁드립니다!

**Comment by 2duckchun** [comment]
죄송합니다. 이번에 회사 내 어플 출시에 개인 사정이 겹쳐 긴 연휴에도 불구하고 작업을 제대로 진행하지 못했습니다.
마감기한을 10월 22일로 늘리되, 퀄리티 있게 작업 하겠습니다.

**Comment by hg-pyun** [comment]
넵 알겠습니다.

**Comment by hilee-hdxwill** [comment]
안녕하세요 혹시 아직 완성이 안되어 있다면 제가 참여해도 괜찮을까요? 아니면 이전 분이 계속 작업 중인걸까요?

**Comment by rickyshu** [comment]
안녕하세요 혹시 아직 작업이 필요한 이슈라면 제가 참여해도 괜찮을까요? 아니면 이전 분이 아직 작업하고 계신 건가요?

**Comment by rickyshu** [comment]
네 PR에 이미 완료하신 것을 보고 comment를 삭제 했습니다! 양질의 자료 잘 참고하겠습니다!

**Comment by hg-pyun** [comment]
머지했습니다. 기여 감사합니다!
