### ISSUE TITLE
[번역 필요] useLayoutEffect

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#750]
useLayoutEffect 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by guesung** [comment]
혹시 번역을 하나 더 해도 된다면, useLayoutEffect도 해보고 싶습니다 !

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by guesung** [comment]
잘 부탁드립니다 😆 😆 

9.23까지 꼭 번역하겠습니다 !!!

**Comment by hg-pyun** [comment]
@guesung 님 혹시 어떻게 진행되고있는지 공유 부탁드려도 될까요 🙇‍♂️

**Comment by 2wheeh** [comment]
@hg-pyun @guesung  안녕하세요 혹시 현재 Assignee 께서 진행이 어렵다고 하시면, 제가 이어받고 싶습니다 ✋🏻

**Comment by hg-pyun** [comment]
별다른 답변이 없으셔서 @2wheeh 님께 다시 어사인 드리도록 하겠습니다. 🙇‍♂️

**Comment by guesung** [comment]
앗 이제 확인했네요 ..! 죄송합니다 ㅜㅜ

넵 !! 알겠습니다

**Comment by 2wheeh** [comment]
> 별다른 답변이 없으셔서 @2wheeh 님께 다시 어사인 드리도록 하겠습니다. 🙇‍♂️

@hg-pyun 잘부탁드립니다. Due Date 10/31 로 작업하겠습니다 !
