### ISSUE TITLE
[번역 필요] useReducer

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#752]
useReducer 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by da-in** [comment]
`useReducer` 작업하고싶습니다!

**Comment by 2duckchun** [comment]
안녕하세요! 제가 작업해보고 싶습니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by 2duckchun** [comment]
영광입니다. 9월 17일(일요일)까지 완료하겠습니다!
