### ISSUE TITLE
[번역 필요] lazy

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#754]
lazy 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by KANGPUNGYUN** [comment]
제가 lazy 페이지 번역하고 싶습니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by KANGPUNGYUN** [comment]
제가 실수로 unassign 눌렀습니다. 다시 assign 부탁드려도 될까요?
이번주 일요일(9월 3일)까지 번역하겠습니다!

**Comment by hg-pyun** [comment]
#767
