### ISSUE TITLE
[번역 필요] flushSync

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#755]
flushSync 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by mnxmnz** [comment]
안녕하세요 flushSync 페이지 번역 희망합니다 :)

**Comment by hg-pyun** [comment]
잘 부탁드립니다! Due Date를 스레드로 남겨주시면 감사하겠습니다. 🙇‍♂️

**Comment by mnxmnz** [comment]
이번주 일요일(9월 2일)까지 작업 완료하겠습니다 🙌

**Comment by hg-pyun** [comment]
#770
