### ISSUE TITLE
[번역 필요]] Community

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#760]
[Community 페이지](https://ko.react.dev/community)에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by caseBread** [comment]
안녕하세요, [Community 페이지](https://ko.react.dev/community) 번역작업 진행해보고 싶습니다.

작업 예상 기간은 ~9.17 입니다.

**Comment by thomas-min** [comment]
안녕하세요. 해당 페이지 번역 희망합니다.
9월 25일(월) 까지 완료 하겠습니다.

**Comment by hg-pyun** [comment]
#780
