### ISSUE TITLE
[번역 필요] Versioning Policy

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#761]
[Versioning Policy](https://ko.react.dev/community/versioning-policy) 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by lerrybe** [comment]
안녕하세요, versioning policy 부분 번역 희망합니다! ☺️
Due date는 9월 20일(수요일)까지로 하고 싶은데 괜찮을까요?

**Comment by gouz7514** [comment]
안녕하세요 해당 페이지 작업 희망합니다!
작업 due date는 9월 22일 (금) 까지로 하겠습니다

**Comment by gouz7514** [comment]
assign이 없길래 진행하지 않고 있었습니다ㅠㅠ 10월 5일 (목) 이내로 진행하도록 하겠습니다
