### ISSUE TITLE
[번역 필요] Docs Contributors

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#763]
[Docs Contributors](https://ko.react.dev/community/docs-contributors) 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by stakbucks** [comment]
안녕하세요! 번역 희망합니다. 9/17(일) 까지 하겠습니다.

**Comment by hg-pyun** [comment]
#779 기여 감사합니다 🙇‍♂️
