### ISSUE TITLE
[번역 필요] React Videos

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#764]
[React Videos](https://ko.react.dev/community/videos) 페이지에 대해 번역해주실 분을 찾습니다. 선착순 댓글로 달아주신분께 assign 하도록 하겠습니다 🙇‍♂️

**Comment by dididy** [comment]
안녕하세요! Due Date는 9월 10일(일요일)까지 제가 번역하고 싶습니다.

**Comment by hg-pyun** [comment]
잘 부탁드립니다!

**Comment by hg-pyun** [comment]
#771
