### ISSUE TITLE
용어: boundary

### ISSUE THREAD

**Issue by KANGPUNGYUN** [reactjs/ko.react.dev#769]
# 논의하고자 하는 용어
`boundary`, `error boundary`

# 해당 용어가 등장하는 원문의 문장

- #767 

> You can do this by wrapping the lazy component or any of its parents into a `<Suspense>` **boundary**:

> If the Promise rejects, React will `throw` the rejection reason for the nearest **Error Boundary** to handle.

`boundary`는 `바운더리`, `경계` 두 가지로 번역되고 있고,  `Error Boundary`는 `에러 경계`로 번역하거나 `Error Boundary`를 번역하지 않고 그대로 사용하는 경우가 있습니다. 다음의 용어를 어느 방향으로 통일하면 좋을 지 의논하고 싶습니다.

In `boundary` and `error boundary`, I would like to discuss whether it is better to write clean up as a unique noun or translate the meaning into Korean.

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by hg-pyun** [comment]
경계는 다른 의미와 혼동의 여지가 있어서 `바운더리` 혹은 원문 그대러 `boundary`를 쓰는게 어떨까 싶습니다.

**Comment by taggon** [comment]
> To solve this problem for React users, React 16 introduces a new concept of an “error boundary”.

[공식 문서에 나와있듯이](https://legacy.reactjs.org/docs/error-boundaries.html#:~:text=To%20solve%20this%20problem%20for%20React%20users%2C%20React%2016%20introduces%20a%20new%20concept%20of%20an%20%E2%80%9Cerror%20boundary%E2%80%9D.), `Error Boundary`는 `Hooks`처럼 React에서 새롭게 정의한 개념이므로 번역하기 보다는 원문을 살리는 게 좋겠다는 의견에 공감합니다.

**Comment by KANGPUNGYUN** [comment]
저도 두 분의 의견처럼 `boundary`는 `경계`로 번역하기 보단 `바운더리`로 작성하고, `Error Boundary`는 원문 그대로 작성하는 것이 좋겠다는 의견입니다.

`boundary`는 `Error Boundary`처럼 통일성 있게 번역하지 않고 원문 그대로 작성하는 것도 좋아보이지만, `boundary`만 번역하지 않고 작성하는 것이 번역된 글에서 가독성이 떨어지는 것처럼 느껴져 특별한 사유가 아닌 이상 `바운더리`로 작성하는 것이 어떨까 싶습니다.(이 의견은 지극히 개인적인 의견입니다.)

**Comment by eomttt** [comment]
저도 원문을 살리는것에 한표 하겠습니다

**Comment by gnujoow** [comment]
원문 그대로 사용에 동의합니다.

**Comment by gnujoow** [comment]
wiki업데이트 완료했습니다 .
