### ISSUE TITLE
[번역 필요] Profiler

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#801]
https://ko.react.dev/reference/react/Profiler

**Comment by hg-pyun** [comment]
@froggy1014 님 께 할당하도록 하겠습니다. Due Date를 남겨주시면 감사하겠습니다 🙇‍♂️

**Comment by froggy1014** [comment]
@hg-pyun 

11월 12일까지 하겠습니다 !

처음이고, 그라운드 룰을 잘 숙지하고 실수없이 하고 싶어서.. 넉넉하게 잡았는데 괜찮을까요?

**Comment by hg-pyun** [comment]
@froggy1014 넵 문제없습니다. 잘 부탁드립니다 🙇‍♂️
