### ISSUE TITLE
[번역 필요] TypeScript 사용하기

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#808]
아래 페이지 번역해주실분을 찾습니다. 원하시는분은 댓글에 Due Date와 함께 남겨주시면 감사하겠습니다!

- https://ko.react.dev/learn/typescript

**Comment by HojinAn** [comment]
14일까지 제가 작업해도 괜찮을까요?

**Comment by hg-pyun** [comment]
@HojinAn 넵 잘부탁드립니다 🙇‍♂️
