### ISSUE TITLE
[번역 필요] 'use client'

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#810]
아래 페이지 번역해주실분을 찾습니다. 원하시는분은 댓글에 Due Date와 함께 남겨주시면 감사하겠습니다!

- https://ko.react.dev/reference/react/use-client

**Comment by HwangSunBeom** [comment]
안녕하세요 :) 14일까지 작업해보고 싶습니다.

**Comment by hg-pyun** [comment]
@HwangSunBeom 님 잘 부탁드립니다 🙇‍♂️

**Comment by HwangSunBeom** [comment]
@hg-pyun 안녕하세요 :)

번역 작업 후 PR 생성해 둔 상태인데 'use-server'와 같이 영문 공식문서 사이트와 내용 차이가 있는 것으로 보입니다.
현재 레포 기준으로 계속 작업을 해도 되는 것인지 문의드립니다.

**Comment by gnujoow** [comment]
resolved by #848
