### ISSUE TITLE
[번역 필요] 'use server'

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#811]
아래 페이지 번역해주실분을 찾습니다. 원하시는분은 댓글에 Due Date와 함께 남겨주시면 감사하겠습니다!

- https://ko.react.dev/reference/react/use-server

**Comment by da-in** [comment]
안녕하세요. 12일까지 작업 진행하고 싶습니다 🙇🏻‍♀️

**Comment by hg-pyun** [comment]
@da-in 잘 부탁드려요! 🙇‍♂️

**Comment by gnujoow** [comment]
> @hg-pyun 안녕하세요!
> 
> 번역 완료 후 맞춤법 검사만 남은 상황인데 영문 공식문서 사이트와 내용에 차이가 있는 것 같아서, 현재 레포 기준으로 계속 작업해도 되는 것인지 문의드립니다. https://react.dev/reference/react/use-server

🙏 진행 부탁드리겠습니다. 원문과 차이가 있는 경우 sync pr이 아직 병합되지 않은 경우일 수 있겠습니다. PR에서 해당 부분이 병합되었는지도 확인 한번 부탁드릴게요
