### ISSUE TITLE
[번역 필요] experimental_taintObjectReference

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#813]
아래 페이지 번역해주실분을 찾습니다. 원하시는분은 댓글에 Due Date와 함께 남겨주시면 감사하겠습니다!

- https://ko.react.dev/reference/react/experimental_taintObjectReference

**Comment by taggon** [comment]
이거는 제가 11월 12일까지 작업하겠습니다.

**Comment by hg-pyun** [comment]
@taggon 감사합니다 🙇‍♂️
