### ISSUE TITLE
용어: Directive

### ISSUE THREAD

**Issue by da-in** [reactjs/ko.react.dev#819]
# 논의하고자 하는 용어
Directive, Directives

# 해당 용어가 등장하는 원문의 문장
API Reference에 Directive가 추가되었습니다.  
https://react.dev/reference/react/directives

Hook 처럼 번역하지 않는 것이 좋을지 논의하면 좋을 것 같습니다.

> **Directives** provide instructions to bundlers compatible with React Server Components.

> To import a Server Action from client code, the **directive** must be used on a module level.

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by HwangSunBeom** [comment]
관련 내용이 https://github.com/reactjs/ko.react.dev/issues/810 에서도 등장해 함께 이야기되면 좋을 것 같습니다.

> When a 'use client' file is imported from another client file, the directive has no effect. 

> To reduce client bundle size and take full advantage of the server, move state (and the 'use client' directives) lower in the tree when possible, and pass rendered server components [as children](https://ko.react.dev/learn/passing-props-to-a-component#passing-jsx-as-children) to client components.

> Because props are serialized across the server–client boundary, note that the placement of these directives can affect the amount of data sent to the client; avoid data structures that are larger than necessary.

> Directives like 'use client' must be at the very beginning of a file, above any imports or other code (comments above directives are OK). They must be written with single or double quotes, not backticks. (The 'use xyz' directive format somewhat resembles the useXyz() Hook naming convention, but the similarity is coincidental.)

**Comment by gnujoow** [comment]
> Directives provide instructions to [bundlers compatible with React Server Components](https://react.dev/learn/start-a-new-react-project#bleeding-edge-react-frameworks).

Directives가 서버 혹은 클라이언트에서 실행되는지 지시해주는 계념으로 이해합니다. "지시어"로 번역을 해보면 어떨까 제안합니다.

**Comment by lumirlumir** [comment]
현재 이슈는 'directive'를 '지시어'로 변경하는 것으로 진행하겠습니다.

**Comment by eomttt** [comment]
https://github.com/reactjs/ko.react.dev/blob/main/wiki/translate-glossary.md

여기에 추가해수제요

**Comment by lumirlumir** [comment]
@eomttt 

#1071 커밋에 이미 포함되어 있습니다
