### ISSUE TITLE
용어: Bundler

### ISSUE THREAD

**Issue by HwangSunBeom** [reactjs/ko.react.dev#829]
# 논의하고자 하는 용어
bundler, bundlers

# 해당 용어가 등장하는 원문의 문장
> When a file marked 'use client' is imported from a server component, [compatible bundlers](https://ko.react.dev/learn/start-a-new-react-project#bleeding-edge-react-frameworks) will treat the import as the “cut-off point” between server-only code and client code.

---

bundle은 다음과 같이 [Translate Glossary](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary) 문서에 언급되어 있지만 bundler는 다루고 있지 않습니다. 이에 bundler를 bundle과 같이 번역하지 않는 것이 좋을지 논의하고 싶습니다.

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by taggon** [comment]
이미 음차한 한글 표현이 많이 사용되는 것으로 보여서 (구글 검색시 대략 50만건 이상) 그대로 음차한 `번들러`를 사용하면 좋을 것 같습니다.

```
... 호환되는 번들러는 이러한 import를 서버 전용 코드와 클라이언트 코드의 기준점으로서 다룹니다.
```

**Comment by HwangSunBeom** [comment]
#823
관련 내용 수정하였습니다. 감사합니다 :)

**Comment by gnujoow** [comment]
번들러는 음차해서 사용하도록 하겟습니다 이슈를 닫습니다.
