### ISSUE TITLE
2023-11-27 Conflict Resolve

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#833]
아래 4개 PR 컨플릭트 리졸브가 필요한데, 작업해주실분 있으실까요 🙏 

- https://github.com/reactjs/ko.react.dev/pull/804
- https://github.com/reactjs/ko.react.dev/pull/806
- https://github.com/reactjs/ko.react.dev/pull/817
- https://github.com/reactjs/ko.react.dev/pull/828

**Comment by taggon** [comment]
일단 #804 는 제가 작업한 부분이 포함되어 있으니까 제가 오늘 작업해보겠습니다.
나머지는 일단 #804 를 진행한 후에 한 번 살펴볼게요!

**Comment by taggon** [comment]
어제 작업해서 Conflicts는 해결했는데 그래도 빌드 실패가 뜨네요.

**Comment by gnujoow** [comment]
제가 살펴보려고 하는데 진행상황을 간략하게 공유받을 수 있을까요?

**Comment by hg-pyun** [comment]
@taggon @gnujoow 잘 부탁드립니다 🙇‍♂️

**Comment by gnujoow** [comment]
이전 pr들이 closed되어서 #839 에서 확인되는 모든 conflict에 대해서 resolve 했습니다.

**Comment by hg-pyun** [comment]
@gnujoow 감사합니다!
