### ISSUE TITLE
용어: Dependencies

### ISSUE THREAD

**Issue by gnujoow** [reactjs/ko.react.dev#841]
# 논의하고자 하는 용어

Dependencies

useEffect, useMemo,  useCallback등 dependencies를 정의에 대한 표현이 다른것을 확인했습니다. 문서간의 통일성을 맞추고자 하나의 표현으로 통일을 제안합니다.

# 해당 용어가 등장하는 원문의 문장

종속성으로 표기하는 경우

https://ko.react.dev/learn/lifecycle-of-reactive-effects 

https://github.com/reactjs/ko.react.dev/blob/b6673d5290cf7e48297e8e6369458a9d7105992c/src/content/learn/lifecycle-of-reactive-effects.md?plain=1#L356

의존성으로 표기하는 경우
https://github.com/reactjs/ko.react.dev/blob/b6673d5290cf7e48297e8e6369458a9d7105992c/src/content/learn/reusing-logic-with-custom-hooks.md?plain=1#L894-L897 

원문 그대로 표기하는 경우
> 아래의 경우 useMemo의 매개변수를 설명하기 위해서 원문 그대로를 사용한듯 보입니다.
https://github.com/reactjs/ko.react.dev/blob/b6673d5290cf7e48297e8e6369458a9d7105992c/src/content/reference/react/useMemo.md?plain=1#L40C1-L43

---

# 논의가 완료된 후에 아래 내용을 업데이트 해주세요
- [ ] https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

**Comment by gnujoow** [comment]
>[종속되다 1 ](https://ko.dict.naver.com/#/entry/koko/1d29bb3e10ce4200b4e3d4d56ca506fd)從屬되다
> 1. 동사 자주성이 없이 주가 되는 것에 딸려 붙게 되다.
> 2. 동사 문장의 구성 성분으로서 다른 부분에 대하여 주술, 수식, 조건적 접속 따위의 관계로 결합하게 되다.
> 명사
> 1.	자주성이 없이 주가 되는 것에 딸려 붙음.
> 정치적 종속.
> 2.	언어 문장의 구성 성분으로서 다른 부분에 대하여 주술, 수식, 조건적 접속 따위의 관계로 결합하는 일. 또는 그런 방식


> [의존하다 ](https://ko.dict.naver.com/#/entry/koko/4f3c18812a094666ba70abeefd3caf5a)依存하다 어휘등급 
> 동사 다른 것에 의지하여 존재하다.
> 명사 다른 것에 의지하여 존재함.

**Comment by gnujoow** [comment]
제안)
dependencies는 우리말로 의존, 종속으로 번역될수 있습니다. 하지만 이 문서에서는 의존성, 의존성 배열등으로 통일하는 것을 제안합니다.

- "종속"은 한 요소가 다른 요소에 완전히 종속되어 자율성이 거의 없는 상태를 의미하는 경우가 많습니다. 반면, "의존"은 한 요소가 다른 요소를 필요로 하지만, 그것이 전체 구조나 시스템에 어떤 영향을 미치는지에 대한 더 폭넓은 의미를 담고 있습니다. 따라서 필요성 혹은 기능간의 연결을 뜻을 포함하는 "의존성"표현이 dependencies를 더 잘 표현한다고 생각합니다.
- 일반적으로 소프트웨어에서 dependency는 의존성으로 번역되는 경우가 많습니다.

**Comment by gnujoow** [comment]
예외 추가)
https://github.com/reactjs/ko.react.dev/blob/b6673d5290cf7e48297e8e6369458a9d7105992c/src/content/reference/react/useMemo.md?plain=1#L21

위 처럼 함수의 매개변수를 설명할때는 원문으로 적되 아래 설명에서는 원문과 번역을 병기한다.
https://github.com/reactjs/ko.react.dev/blob/b6673d5290cf7e48297e8e6369458a9d7105992c/src/content/reference/react/useMemo.md?plain=1#L43
```
 * `dependencies (의존성)`: `calculateValue` 코드
 ```

**Comment by timingsniper** [comment]
Depend라는 동사가 '의존하다'라는 뜻을 가지지만 '종속하다'라는 뜻은 가지고 있지 않기도 하고, @gnujoow 님의 말씀대로 일반적으로 소프트웨어에서 dependency는 의존성으로 번역되는 경우가 많기에 의존성으로의 통일을 제안합니다.

**Comment by taggon** [comment]
패키지 동작을 생각해보면 "의존성"이 맞는 번역입니다.

**Comment by taggon** [comment]
논의가 정리된 것으로 보여서 [용어집](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary)에 'dependency'를 '의존성'으로 번역한다고 추가했습니다. 따라서 현재 논의는 닫겠습니다.
