### ISSUE TITLE
Incorrect href in React learning documentation

### ISSUE THREAD

**Issue by harish-sethuraman** [reactjs/ko.react.dev#851]
https://ko.react.dev/learn/updating-arrays-in-state#making-other-changes-to-an-array

On the above page, the href attribute for '중첩된 JavaScript 객체 업데이트' is incorrect.
It should be corrected to https://ko.react.dev/learn/updating-objects-in-state#updating-a-nested-object.

The translated learning documentation has helped me a lot in my learning.
Thank you.

copy of https://github.com/reactjs/react.dev/issues/6582
(raising a copy as I didn't have access to move issues 😅)

**Comment by hg-pyun** [comment]
> 처음 기여하기 좋은 issue일 것 같습니다 👍 

I think it'll be a good issue to contribute to for the first time. 👍
