### ISSUE TITLE
[번역 필요] Directives

### ISSUE THREAD

**Issue by bottlewook** [reactjs/ko.react.dev#891]
### Summary

한국어 공식문서 [Directives](https://ko.react.dev/reference/react/directives)  번역 제안

### Page

https://ko.react.dev/reference/react/directives

### Details

안녕하세요! 
한국어 공식문서에서 [Directives](https://ko.react.dev/reference/react/directives) 부분이 번역되어 있지않은 것으로 보이는데 제가 해당 페이지 번역을 맡아도 될까요?

**Comment by hg-pyun** [comment]
넵 잘부탁드립니다!
