### ISSUE TITLE
[번역 필요]: meta 

### ISSUE THREAD

**Issue by bottlewook** [reactjs/ko.react.dev#901]
### Summary

한국어 공식문서 [meta](https://ko.react.dev/reference/react-dom/components/meta) 번역 제안

### Page

https://ko.react.dev/reference/react-dom/components/meta

### Details

안녕하세요! 최근 [Directives](https://ko.react.dev/reference/react/directives) 번역을 마치고 새롭게 등장한 meta 컴포넌트에 대한 관심이 생겨 해당 페이지의 번역을 맡아도 되는지 이슈 남겨봅니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다!

**Comment by lumirlumir** [comment]
@bottlewook 안녕하세요😊 혹시 작업 진행중이실까요? 확인 한번 부탁드리겠습니다!

**Comment by Zero-1016** [comment]
@lumirlumir 안녕하세요 😊

혹시 해당 문서 작업 진행중이실까요? 아니면 번역 진행해보고자 합니다!

**Comment by lumirlumir** [comment]
@Zero-1016 맡아서 진행해주시면 감사하죠. 잘 부탁드립니다🙇‍♂️
