### ISSUE TITLE
[번역 필요] preconnect

### ISSUE THREAD

**Issue by jungwoo3490** [reactjs/ko.react.dev#905]
### Summary

한국어 공식 문서 [preconnect](https://ko.react.dev/reference/react-dom/preconnect) 번역 제안

### Page

https://ko.react.dev/reference/react-dom/preconnect

### Details

preconnect 문서가 한글 번역이 안 되어 있어, 이 부분 번역을 신청합니다.

**Comment by hg-pyun** [comment]
잘 부탁드립니다!

**Comment by hg-pyun** [comment]
https://github.com/reactjs/ko.react.dev/pull/924
