### ISSUE TITLE
[번역 필요] React 19 Beta

### ISSUE THREAD

**Issue by mkitwave** [reactjs/ko.react.dev#907]
### Summary

안녕하세요, 현재 React 한국 공식문서의 Blog 항목 중 'React 19 Beta' 문서가 번역되어 있지 않습니다.
19 Beta 버전의 변경점들을 체크해볼 수 있는 문서이니만큼 빠르게 번역되면 좋을 것 같아 기여하고 싶은데요, 따로 번역이 진행되고 있지 않으면 제가 진행해도 좋을 것 같아 이슈 남겨보았습니다. 답변 주시면 감사하겠습니다 🙇

### Page

https://ko.react.dev/blog/2024/04/25/react-19

### Details

@hg-pyun

**Comment by hg-pyun** [comment]
번역해주시면 감사하죠! 잘 부탁드립니다 🙇‍♂️
