### ISSUE TITLE
[번역 필요] React 19 Beta Upgrade Guide

### ISSUE THREAD

**Issue by SayisMe** [reactjs/ko.react.dev#911]
### Summary

안녕하세요. React 19 Beta Upgrade Guide 글에 대해서 번역을 해보고 싶어  이슈 남기게 되었습니다. 혹시 담당해도 괜찮을까요?

### Page

https://react.dev/blog/2024/04/25/react-19-upgrade-guide
https://ko.react.dev/blog/2024/04/25/react-19-upgrade-guide

### Details

~~지금으로부터 일주일 내로 작업하여 완료하도록 하겠습니다. 감사합니다.~~
담당 허가가 되면 해당 시점부터 일주일 동안 작업하도록 하겠습니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다!

**Comment by lumirlumir** [comment]
@SayisMe 안녕하세요😊 혹시 작업 진행중이실까요? 확인 한번 부탁드리겠습니다!
