### ISSUE TITLE
[번역 필요] useSyncExternalStore

### ISSUE THREAD

**Issue by HojinAn** [reactjs/ko.react.dev#913]
Summary
이전 번역(#619) 이후 추가된 항목을 번역하고자 합니다!

Page
https://ko.react.dev/reference/react/useSyncExternalStore

Details
안녕하세요!
[useSyncExternalStore](https://ko.react.dev/reference/react/useSyncExternalStore)의 주의 사항 2가지 이번 주 내로 번역하고자 신청합니다

**Comment by hg-pyun** [comment]
넵 잘 부탁드립니다!
