### ISSUE TITLE
[Typo]: Wiki 내 '국립국어원' 링크

### ISSUE THREAD

**Issue by Hanna922** [reactjs/ko.react.dev#918]
### Summary

안녕하세요. ko.react.dev 웹사이트의 문제는 아니지만, 해당 레포 Wiki 페이지의 [Best-practices-for-translation](https://github.com/reactjs/ko.react.dev/wiki/Best-practices-for-translation) 문서에 포함된 [국립국어원 쌍점 표기](https://www.korean.go.kr/front/page/pageView.do?page_id=P000197&mn_id=30) 링크가 수정되었거나 정상 작동하지 않는 것 같습니다.
감사합니다!

### Page

https://github.com/reactjs/ko.react.dev/wiki/Best-practices-for-translation

### Details

<img width="1165" alt="image" src="https://github.com/reactjs/ko.react.dev/assets/84809236/5b1dc109-a7f6-4538-9fca-f3f91a6b4627">

**Comment by hg-pyun** [comment]
오.. 찾아서 바꿔야겠군요. 제보 감사합니다!

**Comment by wontory** [comment]
> 오.. 찾아서 바꿔야겠군요. 제보 감사합니다!

한국어 어문 규범 링크입니다!
---
쌍점 표기: https://korean.go.kr/kornorms/regltn/regltnView.do?regltn_code=0001&regltn_no=753#a753
쉼표: https://korean.go.kr/kornorms/regltn/regltnView.do?regltn_code=0001&regltn_no=732#a732
