### ISSUE TITLE
[번역 필요] Components and Hooks must be pure

### ISSUE THREAD

**Issue by hyoribogo** [reactjs/ko.react.dev#920]
### Summary

Components and Hooks must be pure 문서를 번역하고자 합니다.

### Page

https://ko.react.dev/reference/rules/components-and-hooks-must-be-pure

### Details

해당 문서가 아직 번역되어 있지 않은데, 제가 번역해도 괜찮을까요?
감사합니다!

**Comment by hg-pyun** [comment]
물론이죠! 잘 부탁드립니다 🙇‍♂️
