### ISSUE TITLE
[번역 필요] Server Actions

### ISSUE THREAD

**Issue by HojinAn** [reactjs/ko.react.dev#923]
### Summary
한국어 공식문서 [Server Actions](https://ko.react.dev/reference/rsc/server-actions) 번역 제안

### Page
https://ko.react.dev/reference/rsc/server-actions

### Details
안녕하세요!
한국어 공식문서에서 [Server Actions](https://ko.react.dev/reference/rsc/server-actions) 부분이 번역되어 있지않은 것으로 확인했는데 해당 페이지 번역을 맡아도 될까요?

6월 8일까지 완료하겠습니다!

**Comment by hg-pyun** [comment]
자주 기여해주셔서 감사합니다. 잘 부탁드립니다 🙇‍♂️
