### ISSUE TITLE
[Suggestion]: Translate-Glossary 검증 자동화

### ISSUE THREAD

**Issue by hg-pyun** [reactjs/ko.react.dev#926]
### Summary

lint와 github action을 통해서 Translate-Glossary 검증 자동화

### Details

https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary 에서 정의한 용어를 현재 리뷰어가 검증하고 있는데요. 이를 eslint와 github action을 통해서 자동화 하고 싶습니다.

**Comment by lumirlumir** [comment]
안녕하세요😊 혹시 현재 이슈가 Assignee를 기다리고 있는 상황인가요? 제가 #971에 유사한 이슈를 올렸는데, Assignee가 없는 상황이라면 제가 진행해보고 싶습니다.
