### ISSUE TITLE
[번역 필요] prefetchDNS

### ISSUE THREAD

**Issue by juheehasaeyo** [reactjs/ko.react.dev#928]
### Summary

한국어 공식 문서 [prefetchDNS](https://ko.react.dev/reference/react-dom/prefetchDNS) 번역 제안입니다!

### Page

https://ko.react.dev/reference/react-dom/prefetchDNS

### Details

prefetchDNS 문서의 한글 번역을 신청합니다!

**Comment by hg-pyun** [comment]
잘 부탁드립니다!
