### ISSUE TITLE
[번역 필요] preinit

### ISSUE THREAD

**Issue by jungwoo3490** [reactjs/ko.react.dev#929]
### Summary

한국어 공식 문서 [preinit](https://ko.react.dev/reference/react-dom/preinit) 번역 제안

### Page

https://ko.react.dev/reference/react-dom/preinit

### Details

preinit 문서가 한글 번역이 안 되어 있어, 이 부분 번역을 신청합니다.

**Comment by hg-pyun** [comment]
잘 부탁드립니다!

**Comment by lumirlumir** [comment]
@jungwoo3490  안녕하세요😊 혹시 작업 진행중이실까요? 확인 한번 부탁드리겠습니다!
