### ISSUE TITLE
[번역 필요]: link

### ISSUE THREAD

**Issue by youngjo-gil** [reactjs/ko.react.dev#931]
### Summary

한국어 공식 문서 컴포넌트 [link](https://ko.react.dev/reference/react-dom/components/link) 페이지 번역 제안

### Page

https://ko.react.dev/reference/react-dom/components/link

### Details

안녕하세요! 한국어 공식문서에 꼭 기여해보고 싶어서 조심스럽게 link 페이지 번역을 맡아서 진행해도 될까요?

**Comment by hg-pyun** [comment]
넵 물론이죠! 잘 부탁드립니다 🙇‍♂️
