### ISSUE TITLE
[번역 필요]: Using TypeScript 페이지

### ISSUE THREAD

**Issue by BangDori** [reactjs/ko.react.dev#932]
### Summary

한국어 공식 문서 [Using TypeScript](https://react.dev/learn/typescript) 페이지 번역 제안

### Page

https://react.dev/learn/typescript

### Details

안녕하세요! Using TypeScript 페이지에 대한 번역이 없는 것 같아서 이 부분 제가 번역을 맡아서 진행해도 될까요??

**Comment by hg-pyun** [comment]
넵 잘부탁드립니다 🙇‍♂️

**Comment by HojinAn** [comment]
앗 지나가다가 보게 되었는데 해당 페이지는 #816 을 통해서 제가 이미 번역 완료해두었습니다! 혹시나 싶어 댓글 남깁니다 ㅎㅎ

Page link
[https://ko.react.dev/learn/typescript](https://ko.react.dev/learn/typescript)

**Comment by BangDori** [comment]
@HojinAn 

앗 그렇군요! 확인해주셔서 감사합니다!! 😁
