### ISSUE TITLE
[번역 필요] hydrateRoot 일부 섹션

### ISSUE THREAD

**Issue by NaGyeong-Park** [reactjs/ko.react.dev#946]
### Summary

API 레퍼런스 > 클라이언트 API > [hydrateRoot](https://ko.react.dev/reference/react-dom/client/hydrateRoot)의 번역이 안된 섹션들 번역

### Page

https://ko.react.dev/reference/react-dom/client/hydrateRoot

### Details

API 레퍼런스 > 클라이언트 API > [hydrateRoot](https://ko.react.dev/reference/react-dom/client/hydrateRoot)의 아래 섹션들의 번역 제가 맡아서 진행해도 괜찮을까요?

- [show-a-dialog-for-uncaught-errors](https://ko.react.dev/reference/react-dom/client/hydrateRoot#show-a-dialog-for-uncaught-errors)
- [displaying-error-boundary-errors](https://ko.react.dev/reference/react-dom/client/hydrateRoot#displaying-error-boundary-errors)
- [show-a-dialog-for-recoverable-hydration-mismatch-errors](https://ko.react.dev/reference/react-dom/client/hydrateRoot#show-a-dialog-for-recoverable-hydration-mismatch-errors)
- [troubleshooting](https://ko.react.dev/reference/react-dom/client/hydrateRoot#troubleshooting)

**Comment by hg-pyun** [comment]
물론입니다! 잘부탁드려요.

**Comment by hg-pyun** [comment]
#951
