### ISSUE TITLE
[번역 필요] script

### ISSUE THREAD

**Issue by juheehasaeyo** [reactjs/ko.react.dev#948]
### Summary

API 레퍼런스 > 컴포넌트 > [<script> 페이지](https://ko.react.dev/reference/react-dom/components/script) 번역을 신청합니다!

### Page

https://ko.react.dev/reference/react-dom/components/script

### Details

안녕하세요!! script 페이지 번역을 맡아 하고싶습니다 :)

**Comment by hg-pyun** [comment]
넵 물론입니다! 잘 부탁드려요 🙇‍♂️

**Comment by hg-pyun** [comment]
#950
