### ISSUE TITLE
[번역 필요] Rules of React

### ISSUE THREAD

**Issue by dlsxjzld** [reactjs/ko.react.dev#949]
### Summary

Rules of React 문서 번역

### Page

https://ko.react.dev/reference/rules

### Details

안녕하세요. 해당 문서에 대한 번역을 추가해도 괜찮을까요? 😊

**Comment by hg-pyun** [comment]
넵 잘 부탁드립니다!

**Comment by hg-pyun** [comment]
#955

**Comment by dlsxjzld** [comment]
> #955

혹시 overview는 번역이 필요 없는 걸까요???
