### ISSUE TITLE
[번역 필요] act

### ISSUE THREAD

**Issue by alstn2468** [reactjs/ko.react.dev#954]
### Summary

API 레퍼런스 > API > act

### Page

https://ko.react.dev/reference/react/act

### Details

해당 페이지가 신규로 추가되면서 번역이 필요할 것 같습니다.
번역자가 없다면 진행해도 괜찮을까요?

**Comment by hg-pyun** [comment]
물론 입니다! 잘 부탁드립니다 🙇‍♂️

**Comment by lumirlumir** [comment]
@alstn2468 안녕하세요😊 혹시 작업 진행중이실까요? 확인 한번 부탁드리겠습니다!

**Comment by alstn2468** [comment]
@lumirlumir 아 신경을 못쓰고 있었습니다..! 혹시나 디른
