### ISSUE TITLE
[Suggestion]: Is `textlint` deprecated?

### ISSUE THREAD

**Issue by lumirlumir** [reactjs/ko.react.dev#971]
### Summary

안녕하세요😊

레포지토리 상의 `textlint`의 사용이 deprecated 되었나 여쭤보고자 합니다.
(#926 이슈와 유사한 내용입니다.)

### Details

`textlint`를 통한 일관된 용어 사용([Wiki](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary))을 통해 문서 개선을 시도하였지만, 해당 lint의 사용이 레포지토리 상에서 deprecated 되었는지 `$ yarn test:textlint` 명령어가 사용 불가함을 확인하였습니다. (관련 [README](https://github.com/reactjs/ko.react.dev/blob/main/textlint/README.md)도 확인하였습니다.)

<details>
<summary>판단 근거</summary>

1. `package.json` 상에 `textlint`와 관련된 `dependencies`가 없고, 이에 따라 `scripts` 상에서도 `test:textlint` 명령어가 존재하지 않음을 확인하였습니다.
2. `.circleci/config.yml` 상에 `test:textlint` 명령어가 존재하지만, 1번의 이유로 인하여 실행이 불가할 것으로 판단됩니다.
3. `textlint`관련 마지막 커밋이 5년 전 입니다.

</details>

React 공식 문서를 읽다 보면 [Wiki](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary) 상에 Translate Glossary로 정리되어있지만, 번역 간 반영이 안되어 있는 경우가 종종 보입니다. 영어를 한글로 번역하다보면, 같은 문맥상의 같은 단어이지만 다르게 해석되는 경우가 종종 발생하는 것 같습니다. 

일관된 용어 사용이 문서의 가독성과 전달력을 더욱 높일 수 있을 것 같아 `textlint`의 사용을 적극 건의하고자 하는데, 혹여 `textlint`를 재사용할(만약 deprecated 되었다면) 예정이 있으신지 궁금합니다. 만약, 재사용 의사가 있으시다면 `package.json`, `textlint/rules`, `textlint/tests` 등을 수정하여 PR을 하고자 합니다.

추가로, #926 에서 관련 내용을 eslint와 github actions를 통해 자동화 할 때, `textlint`와 관련된 부분도 추가되었으면 하는 바람입니다.

**Comment by hg-pyun** [comment]
#926 이 같은 이슈입니다. 이게 장기간 관리가 안되고있어서.. 한번 업데이트가 필요한 시점이기도합니다. 여유가 되신다면, 작업을 해주시면 매우 좋을 것 같습니다 👍

**Comment by lumirlumir** [comment]
넵! 여유되는대로 작업해서 PR 올리도록 하겠습니다👍👍

아, 그리고 현재 궁금한 점이 몇개 있는데,

1. 현재 `.circleci`를 이용하시나요? 사용하지 않으신다면 삭제 후 github actions로 통합하고자 합니다. (개인적인 생각으로는, 한국 및 일본 공식문서에만 존재하는 부분이라, 사용하지 않는다면 삭제하는편이 유지보수에 있어 좀 더 깔끔할 것 같습니다.)
2. textlint의 README 문서 간 아래와 같은 내용이 있는데, 해당 규칙을 따라야 할까요? 번역 및 오타 수정 등의 PR을 주시는 분들이 모두 지켜야 하는 규칙을 작성하는 것이다보니, 'git pre-commit hook에서만 textlint를 실행'할 뿐만 아니라, PR간 '전체 마크다운 파일을 대상'으로 Checks를 진행하는 편이 좋을 것 같다는 생각입니다.
> 모든 글이 번역된 상태가 아니며 번역이 완료되어도 새로운 글은 계속해서 번역이 되어야 하기 때문에 git pre-commit hook에서만 textlint를 실행하며 전체 마크다운 파일을 대상으로 CI에서 실행할 계획은 없습니다. 규칙의 구현에 대한 테스트는 CI에서 실행됩니다.

**Comment by hg-pyun** [comment]
> 현재 .circleci를 이용하시나요? 사용하지 않으신다면 삭제 후 github actions로 통합하고자 합니다. (개인적인 생각으로는, 한국 및 일본 공식문서에만 존재하는 부분이라, 사용하지 않는다면 삭제하는편이 유지보수에 있어 좀 더 깔끔할 것 같습니다.)

그녀석도 레거시의 잔재라 지워도 무방할 것 같습니다.

> textlint의 [README](https://github.com/reactjs/ko.react.dev/blob/main/textlint/README.md) 문서 간 아래와 같은 내용이 있는데, 해당 규칙을 따라야 할까요? 번역 및 오타 수정 등의 PR을 주시는 분들이 모두 지켜야 하는 규칙을 작성하는 것이다보니, 'git pre-commit hook에서만 textlint를 실행'할 뿐만 아니라, PR간 '전체 마크다운 파일을 대상'으로 Checks를 진행하는 편이 좋을 것 같다는 생각입니다.

#963 같이 저희가 번역한 것이 아닌 sync로 올라오는 PR들도 있어서 약간 애매하긴한데.. 걔는 force merge로 어떻게 해결할 수 있을 것 같네요. CI에서 돌리되, 변경된 파일만 체크하는 방식으로 구현하면 조금 더 비용을 아낄 수 있을 것 같습니다.

**Comment by lumirlumir** [comment]
네 그럼 2번 같은 경우는 가능한 README 맞춰서 진행하도록 하겠습니다. 👍

**Comment by lumirlumir** [comment]
@hg-pyun 안녕하세요😊 textlint 개발이 거의 마무리 단계에 접어들고 있습니다.

개발 중 Translate Glossary의 일부를 수정 및 보완하였는데, 해당하는 코드를 통해 translate glossary 문서 생성을 자동화 하고자 합니다.
이를 통해, 코드를 수정하면 그에 맞춰 수기로 translate glossary 문서를 직접 업데이트하는 비효율성을 없앨 수 있습니다.

하지만, 제가 ko.react.dev에 권한이 없어, gitbook 혹은 github wiki에 문서 생성 자동화를 할 수 없는 상태입니다.🥲

그래서 혹시 ko.react.dev에 대한 권한을 받을 수 있을지 여쭙니다.

**Comment by hg-pyun** [comment]
@lumirlumir 권한은 제가 드릴 수 있는게 아니긴 합니다 흑흑.. 개인적으로는 유저에 귀속되지 않도록 Wiki가 아닌 `README.md`처럼 코드레벨로 관리하면 어떨까요? 버전 히스토리도 남고, 누구나 기여할 수 있는 형태가 될 것 같아서 이 편이 훨신 더 접근성이 좋을 것 같습니다.

**Comment by lumirlumir** [comment]
@hg-pyun 좋은 답변 감사드립니다😊

혹시 권한 획득이 불가할 경우, 위와 같이 진행하는게 좋을 것 같아서, 언급해주신 것과 같은 방식의 대안을 고려해두고 있었습니다. 👍👍

우선, textlint PR 이후에, wiki 자동 관리 PR도 올리도록 하겠습니다.  그리고 앞선 2개가 모두 완료되면, CI 환경에서의 자동화 PR까지 진행하도록 하겠습니다
