### ISSUE TITLE
[번역 필요] createRoot 

### ISSUE THREAD

**Issue by icefoxand** [reactjs/ko.react.dev#973]
### Summary
안녕하세요. 리액트 한국어 공식 문서 [createRoot](https://ko.react.dev/reference/react-dom/client/createRoot) 페이지 미번역 부분을 제가 번역해도 괜찮을까요?

### Page
https://ko.react.dev/reference/react-dom/client/createRoot

### Details
해당 페이지에 아래와 같이 영어로 남은 부분이 보여서,, 제가 남은 부분을 번역하고 싶습니다.
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/1f63409c-f267-4c15-83a4-c600598d83e5)
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/7e1d438b-d3bc-4c03-a0c1-a8fe99d57f78)
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/e345f9d1-12e9-4252-b10b-13cb44dc826d)
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/e7e2bc6a-c446-4370-936e-28d6cbf40bb5)

**Comment by hg-pyun** [comment]
물론입니다. 잘 부탁 드려요!

**Comment by icefoxand** [comment]
PR을 방금 올려서, Issue는 종료합니다
