### ISSUE TITLE
[번역 필요]: Rules of React Overview

### ISSUE THREAD

**Issue by junny97** [reactjs/ko.react.dev#979]
### Summary

React 의 규칙 [Overview](https://ko.react.dev/reference/rules) 파트 번역 제안

### Page

https://ko.react.dev/reference/rules

### Details

안녕하세요 React 의 규칙 Overview 파트 번역이 아직 진행되지 않은 것을 확인했습니다. 담당자가 없다면 해당 파트를 맡아서 번역 작업을 진행하고 싶습니다!

**Comment by hg-pyun** [comment]
잘 부탁드려요 🙇‍♂️
