### ISSUE TITLE
[의견 구함] blog의 index.md에 의해, yarn dev 명령이 작동하지 않는 문제 발생

### ISSUE THREAD

**Issue by icefoxand** [reactjs/ko.react.dev#980]
### Summary
맡았던 createRoot 페이지의 번역은 모두 완료했으나, 
현재 yarn dev가 켜지지 않는 문제가 있습니다.
yarn dev가 되지 않으니, 로컬에서 화면을 볼 수가 없어서.. 의견을 구합니다.

### Page
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/be050bb9-e19a-40cb-a261-379cc9a9e29a)

### Details
1. 제 개인 저장소로 포크한 레포지토리를 로컬에 클론했습니다.
2. yarn install로 필요한 디펜던시 모듈을 설치했습니다
3. yarn dev 를 사용하면 아래와 같은 화면이 커맨드창에 뜹니다. 
4. 원인을 확인해보고자, blog 폴더의 index.md를 확인했는데 메타데이터에 title만 있었습니다.
5. https://github.com/reactjs/react.dev 에 들어가서 확인해봐도 blog의 index.md 파일의 메타데이터에는 title 외에 author, date, description 추가 되어있지 않습니다..
6. yarn check-all 이나 캐시를 모두 지우고 2.부터 반복해도 같은 결과가 나옵니다. 어떻게 접근하면 좋을지 의견을 주실 수 있을까요?

<3.과 관련된 화면 1>
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/a8ecb383-f14e-4629-b6ec-c6c77b5f5990)

<3.과 관련된 화면 2>
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/5d314bb0-6aa3-42d6-9d34-56b4f936415e)

<blog의 index.md 파일의 메타데이터>
![image](https://github.com/reactjs/ko.react.dev/assets/92070555/9760f3fb-f878-4bf3-989e-2e17de23e473)

**Comment by lumirlumir** [comment]
안녕하세요, 제가 최근에 해당 문제로 react.dev와 ko.react.dev에 PR을 넣었습니다.

https://github.com/reactjs/ko.react.dev/pull/975

ko.react.dev에는 반영이 되었으니 최신 코드로 pull 하시면 정상 작동 할겁니다😊

**Comment by icefoxand** [comment]
오 감사합니다. 저녁에 다시 최신코드로 해보겠습니다! : )
