### ISSUE TITLE
[Typo]: 'use server' 페이지 from action -> form action 오타수정 요청

### ISSUE THREAD

**Issue by Sunjae95** [reactjs/ko.react.dev#981]
### Summary

![image](https://github.com/reactjs/ko.react.dev/assets/63578094/23b68bae-d62a-40d2-869e-b5d03b421154)

### Page

https://ko.react.dev/reference/rsc/use-server#server-actions-in-forms

### Details

문서 읽다가 원문과 다르게 오타인거 같아서 올립니다.
from -> form 
수정부탁드립니다 :)

**Comment by lumirlumir** [comment]
안녕하세요😊 #982 PR을 통해 수정하였습니다.
