### ISSUE TITLE
[Typo]: Ref로 DOM 조작하기 페이지 "ref 콜백" 링크 누락

### ISSUE THREAD

**Issue by hazzzi** [reactjs/ko.react.dev#984]
### Summary

"Ref로 DOM 조작하기" 페이지의 "ref 콜백을 사용하여 ref 리스트 관리하기" 딥다이브 섹션 내부에서 `"ref 콜백"` 텍스트에 원문과 동일하게 바로가기 링크가 설정되면 좋을 것 같습니다

### Page

https://ko.react.dev/learn/manipulating-the-dom-with-refs#how-to-manage-a-list-of-refs-using-a-ref-callback

### Details

<img width="776" alt="image" src="https://github.com/reactjs/ko.react.dev/assets/33442498/86202784-eae0-4818-9a29-f5f3e927afbc">
원문에서 "ref callback" 텍스트에 링크(https://react.dev/reference/react-dom/components/common#ref-callback)가 걸려있습니다.   
    
<img width="784" alt="image" src="https://github.com/reactjs/ko.react.dev/assets/33442498/86b152bf-10ef-4826-8af8-5420a8f73bb9">
번역 문서에도 원문과 동일하게 https://ko.react.dev/reference/react-dom/components/common#ref-callback 로 연결되는 링크가 걸려있으면 좋을 것 같습니다.

**Comment by hg-pyun** [comment]
제보 감사합니다!
